bluez5: Upgrade 5.41 -> 5.45
Cherry-pick the following commits from oe-core master:

  a751a1f bluez5: Correct support for building without systemd
  62f1122 bluez5: cosmetic fixes to bluetooth bootscript
  f9ccac5 bluez5: update patch status
  bb8bc17 bluez: Correct the timer count for bcm43xx firmware download
  2589cfb bluez5: add more PACKAGECONFIG options
  3202782 bluez5: remove libusb dependency
  30178fe bluez5: Upgrade 5.44 -> 5.45
  476e730 bluez5: cleanup tabs and spaces
  4354fca bluez5: do not install audio.conf
  49d2778 bluez5: add PACKAGECONFIG option for cups
  3eb9a54 bluez5: add PACKAGECONFIG option for systemd
  057f642 bluez5: add PACKAGECONFIG option for midi
  8b433f4 bluez5: remove libasound-module references
  dec3620 bluez5: Upgrade 5.43 -> 5.44
  3985eed bluez5: make readline support conditional.
  2b59c5f bluez5: upgrade to 5.43
  03f0b46 bluez5: Upgrade 5.41 -> 5.42

Plus one additional commit to replace usage of bb.utils.filter() with
bb.utils.contains() (ie use older API for compatibility with OE 2.2).

Full list of original commit messages:

bluez5: Upgrade 5.41 -> 5.42

Bug fixes, add support for new management tracing capability
and marking GATT D-Bus APIs as stable interfaces

Signed-off-by: Maxin B. John <maxin.john@intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 03f0b46520e6a6df7cde37fdb4c27ac6145dff4f)

bluez5: upgrade to 5.43

Signed-off-by: Maxin B. John <maxin.john@intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 2b59c5f90c7d8325ab8893c629b42fb333f3b583)

bluez5: make readline support conditional.

Add readline support to PACKAGECONFIG. If readline needs if left out
of compilation, the bluez utilities which depend on readline are not
included in build or packages.

The defaults in PACKAGECONFIG are the same as before, so there should be
no change to current users.

Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 3985eed70c194c3d9d0c6e94a65e2edfa3f29a8e)

bluez5: Upgrade 5.43 -> 5.44

New feautures/fixes in this version:

* fixes to BLE
* a new midi plugin
* support for single-mode controllers w/o public address
* most of the experimental tools have been promoted and are now part of
  the official tools
* 'experimental' has been renamed to 'testing' (hence the addition of
  the 'testing' package config option)
* classic command line tools like hciattach and hciconfig are now enabled
  by the "--enable-deprecated" configure option (enabled by default for
  backward compatibility).

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit dec3620bd13d43575bcfc5d99f40659672d7252b)

bluez5: remove libasound-module references

Cleanup references to libasound-module since this code has been
completly removed from Bluez.

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 8b433f49c8ea153f75d986e5b9ad89dd3f625cba)

bluez5: add PACKAGECONFIG option for midi

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 057f642b45c740c68c0b10b48eb57c3eac321085)

bluez5: add PACKAGECONFIG option for systemd

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 3eb9a546c0eae4a5ea8526445ba0bf1e7ed5517e)

bluez5: add PACKAGECONFIG option for cups

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 49d27787d48bab371dbacaf44419fc66f697628a)

bluez5: do not install audio.conf

The audio.conf file has been removed, stop installing it.

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 4354fcad22322a80375668bc1beaac9219291136)

bluez5: cleanup tabs and spaces

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 476e730df93223033ba2b3b36cdc47abb3ba30ae)

bluez5: Upgrade 5.44 -> 5.45

Signed-off-by: Maxin B. John <maxin.john@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 30178fed5172d0d8039dea06c32d391eb4a530b8)

bluez5: remove libusb dependency

Not a dependency since version 5.9.

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 3202782d4c76653d83a90122588131e6d945a4e0)

bluez5: add more PACKAGECONFIG options

This patch adds missing PACKAGECONFIG options and allow for a more
fine-grained build of bluez5.

I took care of providing a default configuration that matches the
previous default config.

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 2589cfb8a5b46be958ff3ee228c3a32f82dada86)

bluez: Correct the timer count for bcm43xx firmware download

bcm43xx failed as time out for firmware downloading.
The root cause is that it need wait 50ms to download firmware,
but the value of 50us is set to the timer.

Signed-off-by: Jun Zhu <junzhu@nxp.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit bb8bc17ab8d71e3a30e2f0b655c42434dd968ea4)

bluez5: update patch status

Update the status of following patch from Pending to Accepted:
        a) 0001-hciattach-bcm43xx-fix-the-delay-timer-for-firmware-d.patch

Signed-off-by: Maxin B. John <maxin.john@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit f9ccac5dd359e9b874a39cd879ea23c841085eab)

bluez5: cosmetic fixes to bluetooth bootscript

Fix booting messages wrapped over two different lines:

    Starting bluetooth
    bluetoothd

    Stopping bluetooth
    /usr/libexec/bluetooth/bluetoothd

Also reworked whitespace (removed some empty lines).

Signed-off-by: Javier Viguera <javier.viguera@digi.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 62f1122ef166eba56441d669c6b3b3fe5f367418)

bluez5: Correct support for building without systemd

This avoids the following error when the systemd DISTRO_FEATURE is
enabled, but the systemd PACKAGECONFIG is not:

  ERROR: bluez5-5.46-r0 do_package: SYSTEMD_SERVICE_bluez5 value
  bluetooth.service does not exist

Signed-off-by: Peter Kjellerstedt <peter.kjellerstedt@axis.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit a751a1f4ab0625cbfedb6445b0da080fc455848f)

bluez5.inc: revert bb.utils.filter() -> bb.utils.contains()

Use the older API for compatibility with OE 2.2.

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>